import React from 'react';

/**
 * ReasonList Component
 * Displays adverse action notices or key decision factors generated by the ExplainerAgent.
 */
export default function ReasonList({ reasons = [] }) {
  return (
    <div className="reason-list">
      <h4>Decision Factors & Adverse Reasons</h4>
      {reasons.length === 0 ? (
        <p>No decision factors listed.</p>
      ) : (
        <ul>
          {reasons.map((reason, index) => (
            <li key={index}>{reason}</li>
          ))}
        </ul>
      )}
    </div>
  );
}
